[icons]
icon_depth_0 = static/icons/folder.svg
icon_depth_1 = static/icons/computer.svg
icon_depth_2 = static/icons/globe.svg
icon_depth_3 = static/icons/service.svg
icon_file_json = static/icons/file-json.svg
icon_file_xml = static/icons/file-xml.svg
icon_file_default = static/icons/file.svg
icon_filter = static/icons/filter.svg
icon_exports = icons/floppy_disk.svg

[wordlists]
# raft-large and top-1million are the defaults, change to smaller lists for faster scans
files = /usr/share/wordlists/seclists/Discovery/Web-Content/raft-large-files-lowercase.txt
dirs = /usr/share/wordlists/seclists/Discovery/Web-Content/raft-large-directories-lowercase.txt
subs = /usr/share/wordlists/seclists/Discovery/DNS/subdomains-top1million-110000.txt


[commands]
# Leave empty to use the default built-in script (recommended)
# All placeholders: {target} {hostname} {wordlist} {outfile} {type}
# If nmap output is not -oX the application may break
# If ffuf output is not json the application WILL break
# if unsatisfied with the scans from this website, the default commands are the following
# nmap = nmap -sCV -T4 -p- -v -oX {outfile} {target}
# fuzz = ffuf -mc all -u {target}/FUZZ -w {wordlist} -o {outfile} -of json
# fuzz_subs = ffuf -mc all -u {target} -H "Host: FUZZ.{hostname}" -w {wordlist} -o {outfile} -of json
nmap = nmap -sCV -T4 -p- -v -oX {outfile} {target}
fuzz = ffuf -mc all -u {target}/FUZZ -w {wordlist} -o {outfile} -of json
fuzz_subs = ffuf -mc all -u {target} -H "Host: FUZZ.{hostname}" -w {wordlist} -o {outfile} -of json

[filtering]
auto_filter = true
smart_enabled = true
smart_limit = 1000
status_codes =
word_counts =
lengths =
regex =

[server]
host = 127.0.0.1
port = 5454